version: '3'

services:
  worker-dev:
    build: 
      context: ./nestjs
      
      dockerfile: Dockerfile.dev
    command: yarn start:dev
    ports:
      - "3000:3000"
    volumes:
      - ./nestjs:/usr/app
    depends_on:
      - postgres
    environment: 
      CONNECTION_STRING: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_DATABASE}"

  worker:
    build: 
      context: ./nestjs
      target: production
    image: frankllin15/roxobrasil:worker
    command: yarn start:migrate:prod
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment: 
      CONNECTION_STRING: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_DATABASE}"
    restart: unless-stopped

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_database:/var/lib/postgresql/data
  
volumes:
  postgres_database:
    external: true


